### ISSUE TITLE
Fact-check the site copy

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/chano4mayor#1]

**Comment by beamalsky** [comment]
Fact checking complete! I've made some small changes and put in a set of links that we could use to cite our sources, which I'd like to do if we can present it subtly. All the links are things people could use to get a more full picture of what we're talking about.

**Comment by kalilsn** [comment]
I'm thinking we could do something like [wikipedia's mobile citations](https://en.m.wikipedia.org/wiki/Chance_the_Rapper) to include those links.

**Comment by beamalsky** [comment]
yeah that's what I was thinking of too!

**Comment by beamalsky** [comment]
your favorite
