### ISSUE TITLE
soundcite mobile bug

### ISSUE THREAD

**Issue by kalilsn** [jeancochrane/chano4mayor#11]
On mobile, the soundcite bars are way wider than the text inside of them – anyone know what's up with this?

It doesn't seem to be at all consistent:
![screen shot 2017-03-10 at 6 00 30 pm](https://cloud.githubusercontent.com/assets/473542/23816598/bb535eac-05bb-11e7-8322-bd87c92ae0fa.png)
![screen shot 2017-03-10 at 6 00 17 pm](https://cloud.githubusercontent.com/assets/473542/23816600/bb54e68c-05bb-11e7-8a29-312265e37373.png)
![screen shot 2017-03-10 at 6 00 08 pm](https://cloud.githubusercontent.com/assets/473542/23816596/bb523e32-05bb-11e7-947b-cbf96fee26db.png)
![screen shot 2017-03-10 at 6 00 02 pm](https://cloud.githubusercontent.com/assets/473542/23816597/bb534ee4-05bb-11e7-9ff2-3e8f434e3b32.png)
![screen shot 2017-03-10 at 5 59 56 pm](https://cloud.githubusercontent.com/assets/473542/23816599/bb54134c-05bb-11e7-8dac-0f39572af619.png)

While trying to debug this I've found that changing any of the properties causes it to fix itself immediately, even if they're reset. [Here's a little demonstration.](https://drive.google.com/open?id=0B6d9tIzn9rVMZXpORXdLVVRtNmc) I'm only seeing this on Chrome, seemed fine in Safari although I didn't test on an actual phone.

**Comment by jeancochrane** [comment]
Weird... want to [grab the source](https://github.com/NUKnightLab/soundcite) and host our own version of it that we can tweak? CDNs make me nervous about security holes, anyway.

**Comment by kalilsn** [comment]
Fixed this by giving them "display: inline", not sure why that worked. Going to close and move hosting our own to a different issue.
