### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by kalilsn** [jeancochrane/chano4mayor#12]
Add text citations in the style of wikipedia's mobile site.

- [x] Add citations to html
- [x] Add js/css to make them pop up at the bottom of the page

**Comment by kalilsn** [comment]
Citations are in, with a few possible styles. Let me know what looks best?

**Comment by beamalsky** [comment]
Ok after some deliberation I vote option 2, the highlighting—more subtle
and less academic. What do you all think? I just added full citation text
plus one extra link to the html, also the Site Text doc.

**Comment by kalilsn** [comment]
I think I agree – these don't really need to be citations like you'd have in a paper (and that's not our audience). I think it might be a little **too** subtle at the moment though, anyone have any style suggestions for ways to make it more noticeable? Also, could we have the actual text be a little more conversational rather than formal citation? I'm imagining just a sentence or two either elaborating on the point or previewing the article before the link.

**Comment by beamalsky** [comment]
Hmm if the highlight color was semitransparent black for both it would be a little less subtle. Working on writing more citation text now!

**Comment by beamalsky** [comment]
Should I add them to the HTML and sync, or hold off?
