### ISSUE TITLE
clean up the repository!

### ISSUE THREAD

**Issue by kalilsn** [jeancochrane/chano4mayor#14]
@jeancochrane @beamalsky can you two make sure you have everything that's in progress saved locally (either in another folder or [excluded](https://help.github.com/articles/ignoring-files/#explicit-repository-excludes)).

i want to remove anything from the repo that's not actually used for the site and use google drive to share those things instead, so we can avoid any unnecessary headaches from directory case etc. in the future.

**Comment by beamalsky** [comment]
yep moved mine, jean I didn't touch your final images or wip folders but
I've got the former saved locally

**Comment by jeancochrane** [comment]
I'm all backed up! But here's a quick reminder that even if we didn't have copies saved locally, git automatically backs things up in form of the commit history ;)

**Comment by beamalsky** [comment]
@jeancochrane is this good to close? who's gonna delete those images

**Comment by kalilsn** [comment]
assigning this to me bc i'm working with the illustrations now + i made a few changes on my branch. i'll close it when i have the illustrations working later today!
