### ISSUE TITLE
Title is broken on smallest mobile size

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/chano4mayor#16]
Just noticed this on my phone:

<img width="337" alt="screen shot 2017-03-18 at 12 15 57 pm" src="https://cloud.githubusercontent.com/assets/14170650/24074371/5136eadc-0bd5-11e7-95bc-e13976407a5a.png">

Should be a quick CSS fix – I'll assign myself!

**Comment by kalilsn** [comment]
closing this since it's finished in my latest pr
