### ISSUE TITLE
Site text review

### ISSUE THREAD

**Issue by kalilsn** [jeancochrane/chano4mayor#18]
We should all go through the text one more time and make sure it's all up to date because I suspect a few changes may have been suggested or made in the site text doc that didn't get into the html. Also either finish/merge [this](https://github.com/jeancochrane/chano4mayor/pull/15) or close it.

**Comment by jeancochrane** [comment]
Here's my suggested workflow: Let's copy the current site text to the "Site Text" Google Doc, then do a final round of edits there?

**Comment by jeancochrane** [comment]
@alexsoble @kalilsn @beamalsky Think we're ready to close this?

**Comment by kalilsn** [comment]
i think so!

**Comment by beamalsky** [comment]
yeah! if anyone sees things they'd like to change let's make it part of the post-feedback revision process?
