### ISSUE TITLE
Use our own soundcloud api key

### ISSUE THREAD

**Issue by kalilsn** [jeancochrane/chano4mayor#19]
https://soundcite.knightlab.com/#should-i-api-key

- [x] Apply for api key
- [x] wait a whole dang month
- [ ] Add our own api key to all requests

**Comment by jeancochrane** [comment]
What's the status on this? Still 13 days to go, I'm guessing? The key keeps hitting its limit before the end of the day and it's frustrating.

Also, can I just say: *It's totally nuts that you have to go through a month-long application process to get a Soundcloud API key*

It's like we're renting time on the LHC or something

**Comment by beamalsky** [comment]
"Geez" - Head of Knight Lab, on hearing how long it takes to get a Soundcloud API key

**Comment by kalilsn** [comment]
@jeancochrane Bad news potentially: we're not allowed to use the api ["to create any app that endorses or supports any political position, candidate for political office or any religion."](https://developers.soundcloud.com/docs/api/terms-of-use#privacy). Unclear what this actually means because I just haven't heard *anything*, not even a confirmation email (the application was a google form lol). I also think they might be a little relaxed about it because they haven't banned soundcite yet even though they're clearly in violation by publishing/sharing their api key.

**Comment by jeancochrane** [comment]
Confirmed: Soundcloud is on some kind of power trip

**Comment by kalilsn** [comment]
If we hear from Chance we should ask him for permission to host the songs ourselves and just cut out soundcloud altogether. I think we could probably get away with doing that for acid rain right now since the mixtape was free but I'm not sure if that's even worth it for just one song.
