### ISSUE TITLE
Citation box isn't centered on safari

### ISSUE THREAD

**Issue by kalilsn** [jeancochrane/chano4mayor#20]
Any advice @beamalsky @jeancochrane @alexsoble? I'm stumped.

![screen shot 2017-03-18 at 9 00 22 pm](https://cloud.githubusercontent.com/assets/473542/24077256/ef265faa-0c1d-11e7-8e45-031139579dd5.png)

**Comment by jeancochrane** [comment]
Weird.... doesn't look terrible to me though?

**Comment by beamalsky** [comment]
hmm yeah i thought this was intentional! this is what it looks like in
chrome on my phone

[image: Inline image 1]

**Comment by kalilsn** [comment]
this is how it looks on my phone:

![screenshot_2017-03-18-21-17-26](https://cloud.githubusercontent.com/assets/473542/24077357/315eaca8-0c21-11e7-989f-71789bada4bf.png)

**Comment by kalilsn** [comment]
figured it out: http://stackoverflow.com/a/25919090

**Comment by jeancochrane** [comment]
CSS is wild

**Comment by kalilsn** [comment]
can't believe this is the "right way"
