### ISSUE TITLE
Add social media meta tags

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/chano4mayor#22]
We want Twitter/Facebook to display a cool image when people Tweet the link.

**Comment by jeancochrane** [comment]
Done! Excited to see these in the wild:

<img width="548" alt="screen shot 2017-03-28 at 8 49 12 pm" src="https://cloud.githubusercontent.com/assets/14170650/24434936/0d13bc2e-13f8-11e7-9424-8ecf77ed1dba.png">

**Comment by beamalsky** [comment]
:')
