### ISSUE TITLE
Add an About the 2019 Mayoral Election section

### ISSUE THREAD

**Issue by beamalsky** [jeancochrane/chano4mayor#24]
- [x]  Voter registration info
- [x]  How to keep updated on who's running

**Comment by beamalsky** [comment]
Ok I'm good with all the text in the Site Text doc! 

https://docs.google.com/document/d/1IX2bi34y2y00EOO6SrGxe55iVo-GhdIweq908Y1geuQ/edit

**Comment by alexsoble** [comment]
Same

**Comment by jeancochrane** [comment]
Same! All good @kalilsn?

**Comment by kalilsn** [comment]
Yep, looks great! 🌟 for everyone!

**Comment by kalilsn** [comment]
@alexsoble do you want to add these new changes to that pull request? I'm happy to do it if you don't mind!

**Comment by alexsoble** [comment]
@kalilsn I would love that -- I'm running on a half tank of gas today, kinda under the weather :/

**Comment by beamalsky** [comment]
Ok the more I think about this the more I feel like we should put this new section at the bottom, right above the footer, and break up our dense text sections a little. What do you all think? Having this info at the bottom also gives it a little more gravity.

**Comment by jeancochrane** [comment]
@beamalsky So essentially move it after the Twitter widget? I could see that working.

**Comment by beamalsky** [comment]
yep that's what i'm saying

**Comment by jeancochrane** [comment]
Done in [4d5a284.](https://github.com/jeancochrane/chano4mayor/commit/4d5a284f446d263e7b13a55c496e4bb21f75ab2b)
