### ISSUE TITLE
Content tweaks

### ISSUE THREAD

**Issue by beamalsky** [jeancochrane/chano4mayor#25]
- [x] Switch homelessness to something like "people experiencing homelessness"
- [x] Contact at bottom
- [x] Change second image

**Comment by jeancochrane** [comment]
Fixed 2/3! Mind quickly clarifying the second point ("contact at bottom") @beamalsky? I have a similar bullet point in my notes but I can't quite recall what it's supposed to mean.

**Comment by beamalsky** [comment]
I think this was a change to the footer text, just put it in
