### ISSUE TITLE
Font tweaks

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/chano4mayor#26]
Here are a couple of font tweaks I'm interested in:

### Serifs:
1.
<img width="1055" alt="playfair" src="https://cloud.githubusercontent.com/assets/14170650/24434682/b875ae80-13f6-11e7-8c58-d70e6428891c.png">
2.
<img width="1074" alt="roboto_slab" src="https://cloud.githubusercontent.com/assets/14170650/24434688/c2bfe7fc-13f6-11e7-9251-c46b80973fcd.png">

### Sans serifs:
3.
<img width="1040" alt="lato" src="https://cloud.githubusercontent.com/assets/14170650/24434692/ca85bab6-13f6-11e7-9dc3-76b089e998a8.png">
4.
<img width="1041" alt="raleway" src="https://cloud.githubusercontent.com/assets/14170650/24434693/ce88ff2e-13f6-11e7-92df-87795fe4ac28.png">

### Illustration text

1. (Same font, just lighter)
<img width="1039" alt="lighter_body" src="https://cloud.githubusercontent.com/assets/14170650/24435420/c69c28aa-13fa-11e7-9ca7-71187bd932c6.png">
2.
<img width="1031" alt="raleway_body" src="https://cloud.githubusercontent.com/assets/14170650/24435423/cc528da2-13fa-11e7-91d8-51930e7f99c7.png">

Any of these pop out as looking particularly good to you, @beamalsky @kalilsn @alexsoble?

**Comment by jeancochrane** [comment]
I should note – this is very much optional, and if you like the fonts better as-is feel free to voice your opinion!

**Comment by beamalsky** [comment]
Ooo I really like serif #2 as a header font, and I'd go for making the
lyrics lighter or leaving them as-is. My general rule for font mixing is
that fonts should either be in the same family or markedly different.
Thanks for all these options Jean!

**Comment by kalilsn** [comment]
@jeancochrane I'm not totally sold on either of those serif fonts but maybe I would like it more in the page. Mind posting the names so I can try 'em out?

As for the lyric text, I like the idea of making it a little different from the body, but let's be careful about going lighter. I'd like to at least meet [WCA's AA recommendation](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html) for contrast ratios, which is 4.5:1. What color are you using for the text there?

**Comment by jeancochrane** [comment]
I'm in bed atm, but the names can be found in the alt text of the images if
you click to edit my post above (which I think you should have permissions
to do).

Not sure what color the text is - I just bumped the weight down to 400 from
600. I'd be happy to make the color darker if that improves the contrast.

**Comment by kalilsn** [comment]
@jeancochrane My bad! Thought you meant lighter as in color – this makes more sense. I'm into it!

**Comment by jeancochrane** [comment]
Cool! Assigning to me – I'll bring these changes in as a PR and you can review them.
