### ISSUE TITLE
Site launch

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/chano4mayor#29]
### To do before the launch

-  bot (jean)
    - [x] remove the quotes requirement
    - [x] remove the wordfilter
- screenshots (jean)
    - [x] take screenshots of the quotes on the page and save them as drafts on the twitter
    - [x] post one or two today, queue the rest
- website (kalil)
    - [x] finish accessibility audit and tweaks
    - [x] make sure all changes are pushed up
- twitter (bea)
    - [x] edit the pinned tweet to reflect that quotes aren't necessary anymore

### Launch plan (2pm CST)

- [ ] email everyone we talked to for feedback (everyone)
- [ ] social media blast (everyone)
- [x] follow chance (whoever wants to do the honors)

**Comment by jeancochrane** [comment]
All wrapped up with my pre-launch checklist! Here's the first of the queued tweets:

<img width="624" alt="screen shot 2017-04-02 at 1 21 46 pm" src="https://cloud.githubusercontent.com/assets/14170650/24589849/661f677a-17a7-11e7-9df4-bd0235be4f79.png">

You can see the rest of them on our Buffer profile.

**Comment by jeancochrane** [comment]
Uploading this here so I can import it into the README without storing it in the repo:

<img width="749" alt="chance_quote3" src="https://cloud.githubusercontent.com/assets/14170650/24591169/860cb7cc-17c0-11e7-8450-b549622df7fe.png">

Nothing to see here – move along!

**Comment by kalilsn** [comment]
@jeancochrane can we close this?

**Comment by jeancochrane** [comment]
Sure! As long as you remember to email folks you asked for feedback 📧
