### ISSUE TITLE
Illustrations

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/chano4mayor#3]
- [x] Find source images (5-7)
- [x] Trace them
- [x] Superimpose quotes on top

**Comment by jeancochrane** [comment]
Added in some half-finished B&W illustrations in [768e00d.](https://github.com/jeancochrane/chano4mayor/commit/768e00dc35f28f285ee1181acde69e97dc44d0f5)

Should I color these normally, or add some kind of wash to them? The Twitter profile pic should probably match [the draft that's up now](https://twitter.com/chano4mayor2k19), but I could see the rest of them going in different directions.

**Comment by kalilsn** [comment]
Nice! These look great!

I would say color them normally, but I don't totally know what you mean by a wash?

**Comment by beamalsky** [comment]
love them!! I'm also not sure what you mean by wash, do you have any
examples in mind? I'd be inclined to pick a palate of <5 colors or so that
the illustrations could share, similar to the placeholder images of Monika
and Donte. I totally trust your coloring instincts, though, if you're more
excited about something else!

**Comment by jeancochrane** [comment]
Limited palette sounds like a good idea to me! By "wash" I meant something like the [What is Community Journalism](https://medium.com/city-bureau/what-is-community-journalism-a-graphic-essay-on-civic-media-aed1d7ca771d#.cyu4v23mh), which uses a limited but abstract palette. I think with this project, though, it'll be better for the colors to be more lifelike.

Expect final versions by the end of the night!

**Comment by jeancochrane** [comment]
Color versions are up in the repo! See the [`finals` directory](https://github.com/jeancochrane/chano4mayor/tree/master/images/illustrations/finals) for web-ready PNGs.

Someone else want to handle formatting these into the quotes? I'm sick of looking at them and would appreciate the alley-oop!

**Comment by beamalsky** [comment]
these look so good!!! excited to see them on the site. kalil and i will
figure out formatting—were there any you intended for a particular
placement? I updated the twitter profile image, lmk what you think.

**Comment by jeancochrane** [comment]
Layouts (and the Twitter profile) look great @beamalsky! Excited to see them implemented :) @kalilsn are you on that, or do you need a hand?

**Comment by kalilsn** [comment]
i'm on it! just going to try to squash this Images/images issue once and
for all before i do it.

**Comment by kalilsn** [comment]
done! see this [pr](https://github.com/jeancochrane/chano4mayor/pull/17).
