### ISSUE TITLE
Add Amara pop up

### ISSUE THREAD

**Issue by beamalsky** [jeancochrane/chano4mayor#36]
Suggested text:

> **Update: Chance the Rapper has endorsed [Amara Enyia](https://amaraenyia.com/the-issues/) for mayor!**

>He said: "Amara and I share values and a vision for Chicago that includes equitable education for our kids, reforming our criminal justice system and bringing new kinds of economic opportunities to our communities without causing displacement. I am proud to stand with her as we work toward bringing new leadership to City Hall."

> There's a lot of work left to get her onto the ballot and then into office, but we're thrilled and ready to vote on February 26th, 2019!

**Comment by jeancochrane** [comment]
I like it! Any comments @kalilsn @alexsoble?

**Comment by jeancochrane** [comment]
This should have been closed by #38, but the Soundcite bug in #39 is preventing modal JS from showing up.
