### ISSUE TITLE
Preckwinkle endorsement

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/chano4mayor#43]
Chance endorsed Preckwinkle in the runoff: https://www.wbez.org/shows/wbez-news/chance-the-rapper-backs-preckwinkle-for-mayor/c0e4fcba-bd5a-4106-87ee-1cb00d6127da

Is this something we want to include on the site?

**Comment by beamalsky** [comment]
I'm pretty content to say that this site is now archival and stop updating it. What do you think?

**Comment by jeancochrane** [comment]
I'm fine with that!
