### ISSUE TITLE
Build the site (html, css, js)

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/chano4mayor#7]
Site text [lives here.](https://docs.google.com/document/d/1IX2bi34y2y00EOO6SrGxe55iVo-GhdIweq908Y1geuQ/edit?usp=sharing)

**Comment by kalilsn** [comment]
Renamed this to something a little more descriptive

**Comment by beamalsky** [comment]
Added task: citations

**Comment by kalilsn** [comment]
Closing this because it's basically done, going to break apart followup tasks into new issues.
