### ISSUE TITLE
Make some memes

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/chano4mayor#8]
- [ ] Turn illustrations into tweetable images
- [ ] Think more about a meme generator

**Comment by beamalsky** [comment]
Twitter bot suggested changes:

- Queue tweets + set up approval process
- Limit images to up % that include Chance
- Bot should use hashtag and/or encourage others to use hashtag
- Overlay #ChanoForMayor hashtag and/or our URL
- Personally, I'd like to see an all caps and less rounded font
