### ISSUE TITLE
Write up form email for getting feedback

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/chano4mayor#9]
We can keep it in the [launch doc.](https://docs.google.com/document/d/1fIcgM40S7Nbc4m52Lv39dznELlQUFL-rmVgSHOjwCTs/edit?usp=sharing)

**Comment by alexsoble** [comment]
Added letter to the share folder!

**Comment by jeancochrane** [comment]
Mind dropping a link in here @alexsoble? I know I could go find it, I'm just lazy.

**Comment by alexsoble** [comment]
https://docs.google.com/document/d/1M-HvG4lvH6RQ6eYbqj85_NtKy05xqo_OkGRwSlJvfJ4/edit

**Comment by jeancochrane** [comment]
Thanks Alex! Looks great :)
